---

- name: Configure tzdata area in debconf
  debconf:
    name: 'tzdata'
    question: 'tzdata/Areas'
    vtype: 'select'
    value: '{{ ntp_timezone.split("/")[0] }}'
  register: ntp_debconf_set_area
  when: ntp_timezone is defined and ntp_timezone

- name: Configure tzdata zone in debconf
  debconf:
    name: 'tzdata'
    question: 'tzdata/Zones/{{ ntp_timezone.split("/")[0] }}'
    vtype: 'select'
    value: '{{ ntp_timezone.split("/")[1] }}'
  register: ntp_debconf_set_zone
  when: ntp_timezone is defined and ntp_timezone

  # tzdata ignores debconf answers when configured non-interactively
  # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704089
- name: Configure timezone in /etc/timezone
  copy:
    content: '{{ ntp_timezone }}\n'
    dest: '/etc/timezone'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: ntp_etc_timezone
  when: ntp_timezone is defined and ntp_timezone

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_items: [ 'tzdata', 'libcap2-bin' ]

- name: Reconfigure tzdata
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  when: (ntp_timezone is defined and ntp_timezone) and
        ((ntp_debconf_set_area is defined and ntp_debconf_set_area.changed) or
         (ntp_debconf_set_zone is defined and ntp_debconf_set_zone.changed) or
         (ntp_etc_timezone is defined and ntp_etc_timezone.changed))

  # Install NTPd on all hosts except inside containers
- include: ntpd.yml
  when: ntp is defined and ntp == 'ntpd'

  # Install OpenNTPd on all hosts except inside containers
- include: openntpd.yml
  when: ntp is defined and ntp == 'openntpd'

